# Generated by Django 5.0.1 on 2024-02-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_actv',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_avlb',
            field=models.BooleanField(default=1),
        ),
    ]
