# Generated by Django 5.0.1 on 2024-02-08 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_itm',
            field=models.ManyToManyField(through='api.ord_itm', to='api.item'),
        ),
        migrations.AlterField(
            model_name='ord_itm',
            name='ord_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord_itms', to='api.order'),
        ),
    ]
