# Generated by Django 5.0.1 on 2024-02-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_cnt_alter_item_is_actv_alter_item_is_avlb'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
